/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Amulet": "护身符",
    "Hey. Have a nice day!!!": "嘿。祝你今天愉快！！",
    "Buff": "增益",
    "Combat": "战斗",
    "Equipment": "装备",
    "Level": "等级",
    "Rebirth": "重生",
    "Soul": "灵魂",
    "Tree": "技能树",
    "Stage": "关卡",
    "Ascension": "转生",
    "Every level gives you 2 HP, 1 DMG, 0.5 DEF": "每级给你 2 生命值， 1 伤害， 0.5 防御",
    "Close": "关闭",
    "Unlock new BUFF": "解锁新增益",
    "UPGRADE": "升级",
    "Extra Levels": "额外等级",
    "EQUIPMENT": "装备",
    "Chance to drop equipment:": "装备掉率:",
    "-After 10 stage all buffs become permanent. You can change them after ASCENSION or REBIRTH": "- 10关后所有增益效果变为永久效果。你可以在转生或重生后改变它们。",
    "-Reach 20 stage to gain EXP for buff.": "- 达到20关可以获得增益的经验",
    ": 33% that your DEF will be double when enemy hits you": "：33%几率当敌人击中你时，你的防御将翻倍",
    "Blacksmithing Experience": "锻造经验",
    "Max Level": "最大等级",
    "Open the slot for the ring": "解锁戒指栏位",
    "Reset to stage 1, but you will lose level, tree and equipment.": "重置到第1关，但会失去等级、树和装备。",
    "Ring Slot": "戒指栏",
    "Unlock Amulet Slot.": "解锁护符栏.",
    "Popup AFK": "挂机弹窗",
    "--- Why LevelUp?": "--- 什么是升级?",
    "--- Endless progress?": "--- 无限进度?",
    "AFK doesn't work in Abyss": "AFK在深渊中不起作用",
    "Hi. If you are here that means you wanna know something.": "嗨。如果你在这里，说明你想知道些什么。",
    "I think this title will make sense when you reach 700 level or when you break the reality and open the first dimension. (It's all about future content)": "我认为当你达到700级，或者当你打破现实，打开第一个维度时，这个游戏才会有意义。（这都是关于未来的内容）",
    "When you are AFK enemies are getting stronger. You can kill only 1 enemy per second. Total enemy kills based on max stage passed * 50. You can pass stages until the boss. You can avoid it when the stage boss is lower than max stage minus 15. Exp gain based on current stage and active perks from Tree, Ascension, Rebirth. Buffs and Formations don't work.": "当你在AFK的时候，敌人会变得更强大。你每秒只能击杀一个敌人。基于通过的最大关卡* 50杀死敌人的总数。你可以通过关卡直到boss。当关卡boss低于最大关卡- 15时，你可以避免它。根据当前关卡获得的经验，以及树、转生、重生的主动特权。增益和阵型无效。",
    " Slot": "栏",
    "Rewards": "奖励",
    "Description:": "介绍:",
    "HP MULT:": "生命值乘数:",
    "DMG MULT:": "伤害乘数:",
    "LOOT MULT:": "战利品乘数:",
    "BUFF - Bloot Art (P)": "增益 - 果体艺术 (P)",
    "-As a higher stage, as a higher chance to find a soul": "-作为一个更高的关卡，作为一个找到灵魂的更高机会",
    "-Each soul gives +1 Max Level and +10% EXP.": "-每个灵魂给予 +1 最高等级和 +10% 经验。",
    "-Kill 10 to up soul gathering Tier.": "-击杀 10 敌人提升灵魂收集层级。",
    "-Kill soul to gain ascension shards 1 time": "-击杀灵魂可获得 1 次转生碎片",
    "-P - Permanent after reaching": "- P -达到后永久不变",
    "-Souls appear from 15 stage": "-灵魂从15阶段出现",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "🎯 Target": "🎯 目标",
    "🧹 Reset": "🧹 重置",
    "📥 Import": "📥 导入",
    "📤 Export": "📤 导出",
    "💾 Save": "💾 保存",
    "⚙️ Settings": "⚙️ 设置",
    "🌀 Buffs": "🌀 增益",
    "🔄Reset perks": "🔄 重置特权",
    "🧝 Hero": "🧝 英雄",
    "📝 Logs": "📝 日志",
    "📜 Events": "📜 事件",
    "🌍 Progress": "🌍 进度",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "💀": "💀",
    "💠": "💠",
    "📖": "📖",
    "🔒": "🔒",
    "🔥": "🔥",
    "🔮": "🔮",
    "🥾": "🥾",
    "🧥": "🧥",
    "ℹ️": "ℹ️",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': '最大',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Level: ": "等级: ",
    // "👾 ": "👾 ",
    "You dropped the ": "你掉落了 ",
    "Lvl ": "等级 ",
    "Points: ": "点数: ",
    "TIER[": "层级[",
    "TOTAL: ": "总计: ",
    "Boots": "靴子",
    "Body": "身体",
    "Iron Sword": "铁剑",
    "Leather Armor": "皮甲",
    "Leather Boots": "皮靴",
    "Rusty Sword": "生锈的剑",
    "Sword": "剑",
    "Chainmail": "锁子甲",
    "Scout Boots": "侦查靴",
    "Active: ": "活跃: ",
    "Invisible": "隐形",
    "Racer": "转台",
    "Solid Body": "固体",
    "Wisdom": "智慧",
    "Endurance": "耐力",
    "Strength": "力量",
    "First Strike": "先发制人",
    "Ring": "戒指",
    "Shards:": "碎片:",
    "Total shards: ": "总计碎片: ",
    "Steel Blade": "钢刃",
    "Cloth Armor": "布甲",
    "Worn Slippers": "旧拖鞋",
    "Souls": "灵魂",
    "BUFF EXP MULT - ": "增益经验乘数 - ",
    "Ascend Shards MULT When you Ascend - ": "转生时转生碎片乘数 - ",
    "Weapon Chance per SOUL TIER - ": "每个灵魂层级武器掉率 - ",
    "Knight’s Edge": "骑士之刃",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " EXP": " 经验值",
    "33% that your DEF will be double when enemy hits you": "：33%几率当敌人击中你时，你的防御将翻倍",
    "35% to block the enemy attack to 1 DMG": "35%几率格挡敌人的攻击到 1 伤害",
    " after Ascension)": " 在转生后)",
    "Deal double DMG by First attack": "第一次攻击造成双倍伤害。",
    "First attack is always critical": "第一次攻击总是暴击。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^🛡️(.+)$/,
    /^⚔️(.+)$/,
    /^👾(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^🧘\[\-([\d\.,]+)\]$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^T\[([\d\.,]+)\]$/,
    /^ T\[([\d\.,]+)\]$/,
    /^([\d\.,]+) 🌌$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Endgame content is (.+) Level\(Abyss (.+)\)$/, '终局内容是 $1 级（深渊 $2）'],
    [/^You gain (.+) ascension shards$/, '你将获得 $1 转生碎片'],
    [/^\[T([\d\.]+)\]: ([\d\.]+)\% \- \[MAX \- ([\d\.]+)\]$/, '\[T$1\]: $2\% \- \[最大 \- $3\]'],
    [/You dropped the Leather Boots (.+)$/, '你掉落了 皮靴 $1'],
    [/You dropped the Chainmail (.+)$/, '你掉落了 锁子甲 $1'],
    [/You dropped the Scout Boots (.+)$/, '你掉落了 侦查靴 $1'],
    [/^Offline bonus for (.+)\n(.+)\(MAX \- (.+)h\). You gained (.+) EXP.  Buff EXP (.+). You passed from (.+) stage (.+) zone \-\> (.+) stage (.+) zone$/, '离线 $1 的奖励\n$2(最大 - $3小时）。获得 $4 经验，增益经验 $5。你从 区域 $7 关卡 $6 -> $9 关卡 $8'],
    [/^Offline bonus for (.+)\n(.+)\(MAX \- (.+)h\). You gained (.+) EXP. Buff EXP (.+). You passed from (.+) stage (.+) zone \-\> (.+) stage (.+) zone$/, '离线 $1 的奖励\n$2(最大 - $3小时）。获得 $4 经验，增益经验 $5。你从 区域 $7 关卡 $6 -> $9 关卡 $8'],
    [/^Offline bonus for (.+)\n(.+)\(MAX \- (.+)h\). You gained (.+) EXP. Buff EXP (.+)$/, '离线 $1 的奖励\n$2(最大 - $3小时）。获得 $4 经验，增益经验 $5'],
    [/^(.+) kills \(Zone (.+) , Stage (.+)\)$/, '$1 击杀（区域 $2，关卡 $3）'],
    [/^(.+) Shard of Dusk (.+)$/, '$1 黄昏碎片 $2'],
    [/^(.+) Veiled Wraith (.+)$/, '$1 面纱魔灵 $2'],
    [/^(.+) Ashen Echo (.+)$/, '$1 灰色回声 $2'],
    [/^(.+) Ebon Spark (.+)$/, '$1 乌木火花 $2'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+)\% DEF$/, '\+$1\% 防御'],
    [/^\+([\d\.]+) MULT EXP for each tier of equipment$/, '\+$1 每层装备的多重经验'],
    [/^\+([\d\.]+) HP$/, '\+$1 生命值'],
    [/^\+([\d\.]+) MULT DMG$/, '\+$1 多重伤害'],
    [/^\+([\d\.]+) Max Level$/, '\+$1 最大等级'],
    [/^\+([\d\.]+) MAX LEVEL$/, '\+$1 最大等级'],
    [/^\+([\d\.]+) ATTACK PER SECOND$/, '\+$1 攻击每秒'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^You killed (.+) and gained (.+) exp$/, '成功击杀 $1，获得 $2 经验'],
    [/^Unlock T([\d\.,]+) Body$/, '解锁 T$1 身体'],
    [/^Unlock T([\d\.,]+) Boots$/, '解锁 T$1 靴子'],
    [/^Unlock T([\d\.,]+) Ring$/, '解锁 T$1 戒指'],
    [/^Unlock T([\d\.,]+) Sword$/, '解锁 T$1 剑'],
    [/^Reach ([\d\.,]+) stage$/, '达到 $1 关'],
    [/^TIER ([\d\.,]+)$/, '层 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);